const API = 'https://web-production-9c1ab.up.railway.app/api';
let mode='owner'; let token=localStorage.getItem('token'); let currentShop=null; let dashboardUnlocked=false;
const $=s=>document.querySelector(s); const views=['login-view','register-view','shop-view','dashboard-view'];
function show(id){views.forEach(v=>$('#'+v).classList.toggle('hidden',v!==id));}
function notice(message,error=true){$('#notice').textContent=message;$('#notice').classList.remove('hidden');$('#notice').style.background=error?'#fff0ed':'#e7f7f2';setTimeout(()=>$('#notice').classList.add('hidden'),4500)}
async function request(path, options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Não foi possível concluir a operação');return data}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
async function loadShops(){const shops=await request('/shops');$('#shop-list').innerHTML=shops.length?shops.map(s=>`<button class="shop-card" data-id="${s.id}"><span>LOJA ${s.shop_number}</span><strong>${s.shop_name}</strong><span>Plano ativo até ${new Date(s.plan_expires_at).toLocaleDateString('pt-BR')}</span></button>`).join(''):'<p>Nenhuma loja ativa encontrada.</p>';document.querySelectorAll('.shop-card').forEach(card=>card.onclick=()=>selectShop(shops.find(s=>s.id===card.dataset.id)));}
async function selectShop(shop){currentShop=shop;$('#selected-shop-name').textContent=shop.shop_name;const products=await request(`/shops/${shop.id}/products`);$('#product-count').textContent=`${products.length} itens`;$('#products').innerHTML=products.map(productCard).join('')||'<p>Esta loja ainda não publicou produtos.</p>';$('#product-area').classList.remove('hidden');document.querySelectorAll('.shop-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===shop.id));}
function productCard(p){return `<article class="product-card">${p.image_url?`<img src="${p.image_url}" alt="${p.name}">`:''}<div class="product-info"><strong>${p.name}</strong><p>${p.description||'Produto disponível na loja.'}</p><span class="price">R$ ${(p.price/100).toFixed(2).replace('.',',')}</span></div></article>`}
function dashboardProductCard(p){return `<article class="product-card"><div class="product-info"><strong>${p.name}</strong><p>${p.description||'Produto disponível na loja.'}</p><span class="price">R$ ${(p.price/100).toFixed(2).replace('.',',')}</span><button class="text-button delete-product" data-id="${p.id}">Excluir produto</button></div></article>`}
async function login(event){event.preventDefault();try{const data=await request('/auth/login',{method:'POST',body:JSON.stringify({...formData(event.target),type:mode,username:mode==='customer'?event.target.username.value.replace(/\D/g,''):event.target.username.value})});token=data.token;localStorage.setItem('token',token);currentShop=data.shop;$('#welcome-title').textContent=`Olá, ${data.user.name||data.user.username}`;$('#logout-button').classList.remove('hidden');show('shop-view');await loadShops();if(mode==='customer')$('#dashboard-button').classList.add('hidden');else $('#dashboard-button').classList.remove('hidden')}catch(e){notice(e.message)}}
async function register(event){event.preventDefault();try{const data=await request('/auth/register',{method:'POST',body:JSON.stringify(formData(event.target))});token=data.token;localStorage.setItem('token',token);currentShop=data.shop;$('#welcome-title').textContent=`Olá, ${data.user.name}`;$('#logout-button').classList.remove('hidden');show('shop-view');await loadShops();notice('Acesso criado com sucesso.',false)}catch(e){notice(e.message)}}
async function openDashboard(){if(!dashboardUnlocked){const password=prompt('Digite a senha do dashboard');if(!password)return;try{await request('/auth/dashboard',{method:'POST',body:JSON.stringify({password})});dashboardUnlocked=true}catch(e){notice(e.message);return}}show('dashboard-view');$('#dashboard-title').textContent=currentShop.shop_name;const [stats,products]=await Promise.all([request('/stats'),request('/products')]);$('#metric-products').textContent=stats.totalProducts||0;$('#metric-orders').textContent=stats.ordersThisMonth||0;$('#metric-sales').textContent=`R$ ${((stats.salesThisMonth||0)/100).toFixed(2).replace('.',',')}`;$('#dashboard-products').innerHTML=products.map(dashboardProductCard).join('')||'<p>Nenhum produto criado.</p>';document.querySelectorAll('.delete-product').forEach(button=>button.onclick=async()=>{if(!confirm('Excluir este produto?'))return;try{await request(`/products/${button.dataset.id}`,{method:'DELETE'});await openDashboard();notice('Produto excluído.',false)}catch(e){notice(e.message)}})}
$('#login-form').onsubmit=login;$('#register-form').onsubmit=register;$('#show-register').onclick=()=>show('register-view');$('#back-login').onclick=()=>show('login-view');$('#dashboard-button').onclick=openDashboard;$('#back-shop').onclick=()=>show('shop-view');$('#logout-button').onclick=()=>{token=null;localStorage.removeItem('token');dashboardUnlocked=false;show('login-view');$('#logout-button').classList.add('hidden')};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{mode=tab.dataset.mode;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));$('#username-label').firstChild.textContent=mode==='customer'?'CPF ': 'Usuário ';$('#show-register').classList.toggle('hidden',mode!=='customer')});$('#new-product').onclick=()=>$('#product-form').classList.remove('hidden');$('#cancel-product').onclick=()=>$('#product-form').classList.add('hidden');$('#product-form').onsubmit=async e=>{e.preventDefault();try{await request('/products',{method:'POST',body:JSON.stringify({...formData(e.target),price:Number(e.target.price.value),stock:Number(e.target.stock.value)})});e.target.reset();e.target.classList.add('hidden');await openDashboard();notice('Produto criado.',false)}catch(err){notice(err.message)}};
if(token){$('#logout-button').classList.remove('hidden');show('shop-view');loadShops().catch(()=>{token=null;localStorage.removeItem('token');show('login-view')})}
